version: '3'
services:
    schlop:
        build: .
        image: schlop
        command: schlop
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - schlop
