# -*- restclient -*-
#

:api = http://127.0.0.1:8000



#
# Users
#

GET :api/users

#

POST :api/users
Content-Type: application/json

{
    "email": "foo2@bar.com"
}


#
# Lists
#


GET :api/shopping_lists

#

POST :api/shopping_lists
Content-Type: application/json
{
    "name": "Another list",
    "creatorId": 3
}


#
# Items
#

GET :api/shopping_lists/3/items

#

POST :api/shopping_lists/3/items
Content-Type: application/json

{
    "description": "Toes"
}